// jsMathSnippets.js

export const jsMathSnippets = [
  { method: 'abs(x)', example: `console.log(Math.abs(-7)); // 7` },
  { method: 'acos(x)', example: `console.log(Math.acos(1)); // 0` },
  { method: 'acosh(x)', example: `console.log(Math.acosh(1)); // 0` },
  { method: 'asin(x)', example: `console.log(Math.asin(0)); // 0` },
  { method: 'asinh(x)', example: `console.log(Math.asinh(1)); // 0.881...` },
  { method: 'atan(x)', example: `console.log(Math.atan(1)); // 0.785...` },
  { method: 'atan2(y, x)', example: `console.log(Math.atan2(1, 1)); // 0.785...` },
  { method: 'atanh(x)', example: `console.log(Math.atanh(0.5)); // 0.549...` },
  { method: 'cbrt(x)', example: `console.log(Math.cbrt(27)); // 3` },
  { method: 'ceil(x)', example: `console.log(Math.ceil(4.2)); // 5` },
  { method: 'clz32(x)', example: `console.log(Math.clz32(1)); // 31` },
  { method: 'cos(x)', example: `console.log(Math.cos(Math.PI)); // -1` },
  { method: 'cosh(x)', example: `console.log(Math.cosh(0)); // 1` },
  { method: 'E', example: `console.log(Math.E); // 2.718...` },
  { method: 'exp(x)', example: `console.log(Math.exp(1)); // 2.718...` },
  { method: 'expm1(x)', example: `console.log(Math.expm1(1)); // 1.718...` },
  { method: 'f16round(x)', example: `console.log(Math.f16round(1.337)); // 1.3359375` },
  { method: 'floor(x)', example: `console.log(Math.floor(4.9)); // 4` },
  { method: 'fround(x)', example: `console.log(Math.fround(1.337)); // 1.3370000123977661` },
  { method: 'LN2', example: `console.log(Math.LN2); // 0.693...` },
  { method: 'LN10', example: `console.log(Math.LN10); // 2.302...` },
  { method: 'log(x)', example: `console.log(Math.log(1)); // 0` },
  { method: 'log10(x)', example: `console.log(Math.log10(100)); // 2` },
  { method: 'LOG10E', example: `console.log(Math.LOG10E); // 0.434...` },
  { method: 'log1p(x)', example: `console.log(Math.log1p(0)); // 0` },
  { method: 'log2(x)', example: `console.log(Math.log2(8)); // 3` },
  { method: 'LOG2E', example: `console.log(Math.LOG2E); // 1.442...` },
  { method: 'max(x1, x2, ...)', example: `console.log(Math.max(1, 5, 3)); // 5` },
  { method: 'min(x1, x2, ...)', example: `console.log(Math.min(1, 5, 3)); // 1` },
  { method: 'PI', example: `console.log(Math.PI); // 3.141...` },
  { method: 'pow(x, y)', example: `console.log(Math.pow(2, 3)); // 8` },
  { method: 'random()', example: `console.log(Math.random()); // random number between 0 and 1` },
  { method: 'round(x)', example: `console.log(Math.round(4.6)); // 5` },
  { method: 'sign(x)', example: `console.log(Math.sign(-3)); // -1` },
  { method: 'sin(x)', example: `console.log(Math.sin(Math.PI / 2)); // 1` },
  { method: 'sinh(x)', example: `console.log(Math.sinh(0)); // 0` },
  { method: 'sqrt(x)', example: `console.log(Math.sqrt(16)); // 4` },
  { method: 'SQRT1_2', example: `console.log(Math.SQRT1_2); // 0.707...` },
  { method: 'SQRT2', example: `console.log(Math.SQRT2); // 1.414...` },
  { method: 'tan(x)', example: `console.log(Math.tan(0)); // 0` },
  { method: 'tanh(x)', example: `console.log(Math.tanh(1)); // 0.761...` },
  { method: 'trunc(x)', example: `console.log(Math.trunc(4.9)); // 4` },
];
