export const jsStringSnippets = [
  { method: 'at()', example: `const str = 'hello';\nconsole.log(str.at(1)); // 'e'` },
  { method: 'charAt()', example: `const str = 'world';\nconsole.log(str.charAt(0)); // 'w'` },
  { method: 'charCodeAt()', example: `const str = 'abc';\nconsole.log(str.charCodeAt(0)); // 97` },
  { method: 'codePointAt()', example: `const str = '𝒳';\nconsole.log(str.codePointAt(0)); // 120120` },
  { method: 'concat()', example: `const str1 = 'Hello';\nconst str2 = 'World';\nconsole.log(str1.concat(' ', str2)); // 'Hello World'` },
  { method: 'constructor', example: `const str = 'abc';\nconsole.log(str.constructor === String); // true` },
  { method: 'endsWith()', example: `const str = 'hello world';\nconsole.log(str.endsWith('world')); // true` },
  { method: 'fromCharCode()', example: `console.log(String.fromCharCode(72, 101, 108, 108, 111)); // 'Hello'` },
  { method: 'includes()', example: `const str = 'javascript';\nconsole.log(str.includes('script')); // true` },
  { method: 'indexOf()', example: `const str = 'banana';\nconsole.log(str.indexOf('a')); // 1` },
  { method: 'isWellFormed()', example: `const str = 'abc';\nconsole.log(str.isWellFormed()); // true` },
  { method: 'lastIndexOf()', example: `const str = 'banana';\nconsole.log(str.lastIndexOf('a')); // 5` },
  { method: 'length', example: `const str = 'hello';\nconsole.log(str.length); // 5` },
  { method: 'localeCompare()', example: `console.log('a'.localeCompare('b')); // -1` },
  { method: 'match()', example: `const str = 'abc123';\nconsole.log(str.match(/\d+/)); // ['123']` },
  { method: 'matchAll()', example: `const str = 'test1test2';\n[...str.matchAll(/test\d/g)].forEach(m => console.log(m[0]));` },
  { method: 'padEnd()', example: `const str = '5';\nconsole.log(str.padEnd(3, '0')); // '500'` },
  { method: 'padStart()', example: `const str = '5';\nconsole.log(str.padStart(3, '0')); // '005'` },
  { method: 'prototype', example: `console.log(typeof String.prototype); // 'object'` },
  { method: 'repeat()', example: `console.log('ha'.repeat(3)); // 'hahaha'` },
  { method: 'replace()', example: `const str = 'hello world';\nconsole.log(str.replace('world', 'there')); // 'hello there'` },
  { method: 'replaceAll()', example: `const str = 'a-b-c';\nconsole.log(str.replaceAll('-', '+')); // 'a+b+c'` },
  { method: 'search()', example: `const str = 'hello123';\nconsole.log(str.search(/\d/)); // 5` },
  { method: 'slice()', example: `const str = 'abcdef';\nconsole.log(str.slice(1, 4)); // 'bcd'` },
  { method: 'split()', example: `const str = 'a,b,c';\nconsole.log(str.split(',')); // ['a', 'b', 'c']` },
  { method: 'startsWith()', example: `const str = 'javascript';\nconsole.log(str.startsWith('java')); // true` },
  { method: 'substr()', example: `const str = 'abcdef';\nconsole.log(str.substr(1, 3)); // 'bcd'` },
  { method: 'substring()', example: `const str = 'abcdef';\nconsole.log(str.substring(1, 4)); // 'bcd'` },
  { method: 'toLocaleLowerCase()', example: `const str = 'HELLO';\nconsole.log(str.toLocaleLowerCase()); // 'hello'` },
  { method: 'toLocaleUpperCase()', example: `const str = 'hello';\nconsole.log(str.toLocaleUpperCase()); // 'HELLO'` },
  { method: 'toLowerCase()', example: `const str = 'HELLO';\nconsole.log(str.toLowerCase()); // 'hello'` },
  { method: 'toString()', example: `const str = new String('abc');\nconsole.log(str.toString()); // 'abc'` },
  { method: 'toUpperCase()', example: `const str = 'hello';\nconsole.log(str.toUpperCase()); // 'HELLO'` },
  { method: 'toWellFormed()', example: `const str = 'abc';\nconsole.log(str.toWellFormed()); // 'abc'` },
  { method: 'trim()', example: `const str = '  hello  ';\nconsole.log(str.trim()); // 'hello'` },
  { method: 'trimEnd()', example: `const str = '  hello  ';\nconsole.log(str.trimEnd()); // '  hello'` },
  { method: 'trimStart()', example: `const str = '  hello  ';\nconsole.log(str.trimStart()); // 'hello  '` },
  { method: 'valueOf()', example: `const str = new String('abc');\nconsole.log(str.valueOf()); // 'abc'` },
];
